version: "3"
services:
    web:
        build: './Poc.Api'
        ports:
            - 5000:5000
        #env:
        #- name: cassandra-endpoint
        #  value: "localhost:000"
        #- name: elastic-endpoint
        #  value: "localhost:000"
    ui:
        build: './Lbs.UI'
        ports:
            - 3000:80
        #env:
        #- name: cassandra-endpoint